/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    cards: Card;
    collections: Collection;
    'card-images': CardImage;
    redirects: Redirect;
    'seo-history': SeoHistory;
    'image-name-claims': ImageNameClaim;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    cards: CardsSelect<false> | CardsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'card-images': CardImagesSelect<false> | CardImagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'seo-history': SeoHistorySelect<false> | SeoHistorySelect<true>;
    'image-name-claims': ImageNameClaimsSelect<false> | ImageNameClaimsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Карточка открытки. URL — /otkrytki/<slug>, один навсегда. Новая запись создаётся в draft с noindex; публикует и открывает в индекс только человек.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards".
 */
export interface Card {
  id: number;
  /**
   * Заголовок страницы (title). Уникален в пределах каталога — совпадения проверяются при сохранении (задача Э5-01). Смена заголовка URL не меняет.
   */
  title: string;
  /**
   * H1 страницы. Пустой — совпадает с title (ТЗ §8.1).
   */
  h1?: string | null;
  /**
   * URL записи: /otkrytki/<slug>. Неизменяем после первой публикации (смена возможна только вместе с одиночным 301 — задача Э1-09). Смена заголовка URL не меняет.
   */
  slug: string;
  /**
   * Изображение открытки (ТЗ §8.1). Обязательно до перевода в review. После первой публикации сменить изображение может только admin: адреса всех производных при этом меняются (ТЗ §6.7), а URL файла постоянен (ТЗ §6.3). URL самой карточки не меняется никогда.
   */
  image?: (number | null) | CardImage;
  /**
   * Естественное описание изображения, не перечень ключей. Обязателен до перевода в review (проверка полноты — задача Э1-08).
   */
  alt?: string | null;
  /**
   * Подпись или текст поздравления, видимый на странице.
   */
  caption?: string | null;
  /**
   * Описание открытки для страницы (видимый текст).
   */
  description?: string | null;
  /**
   * Meta description. Задаётся отдельно от видимого описания (ТЗ §8.1). Совпадения по каталогу проверяются при сохранении (задача Э5-01). index,follow не применяется, пока пусто meta description: страница без непустого описания понижается до noindex,follow и не попадает в sitemap. Поэтому сохранение с index,follow и пустым описанием отклоняется — иначе решение осталось бы в поле и не действовало на сайте.
   */
  metaDescription?: string | null;
  /**
   * Условия использования изображения. Из этого поля берутся license и copyrightNotice в JSON-LD ImageObject (этап 3): если условия у открытки общие, поле остаётся пустым и подставляются условия проекта.
   */
  usageTerms?: string | null;
  /**
   * Подборки, в которые входит открытка (m:n, ТЗ §8.1). ПЕРВАЯ — основная: из неё строятся хлебные крошки. Открытка входит в несколько подборок БЕЗ дублирования URL: канонический адрес карточки остаётся один навсегда — /otkrytki/<slug>, копии карточки внутри подборок не создаются. В ПАКЕТНОЙ операции (ТЗ §8.5, массовая привязка) значение читается как «добавить вдобавок»: уже выбранные подборки сохраняются в прежнем порядке, поэтому основная не переставляется; отвязать пакетом нельзя.
   */
  collections?: (number | Collection)[] | null;
  /**
   * draft → review → published. Перевод в published — осознанное действие человека с ролью admin; сервисный аккаунт ai-editor доводит запись до review.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * index,follow — только для published и только по решению администратора при выполнении условий п. 5.1 SEO ТЗ (подтверждённый спрос, отдельный интент, достаточный объём, уникальные тексты, страница в навигации). index,follow не применяется, пока пусто meta description: страница без непустого описания понижается до noindex,follow и не попадает в sitemap. Поэтому сохранение с index,follow и пустым описанием отклоняется — иначе решение осталось бы в поле и не действовало на сайте.
   */
  robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
  /**
   * Пусто = self-canonical (норма). Переопределение — только администратор и только путём от корня: абсолютный URL собирается из SITE_URL, вручную его вписывать нельзя.
   */
  canonical?: string | null;
  /**
   * Дата первой публикации. Ставится автоматически при первом переводе в published (Э1-08) и далее не меняется: по ней определяется, что URL уже был известен поисковику.
   */
  publishedAt?: string | null;
  /**
   * Меняется ТОЛЬКО при содержательном обновлении: это lastmod в sitemap. Техническая правка (опечатка, служебное поле) дату не двигает — иначе lastmod перестаёт что-либо означать для поисковика.
   */
  updatedContentAt?: string | null;
  /**
   * Заполняется при переводе опубликованной записи в draft или review. Без решения снятие с публикации отклоняется: этот URL уже известен поисковику, и молчаливое исчезновение страницы — это либо потерянный вес ссылки, либо мягкий 404.
   */
  withdrawal?: {
    /**
     * Снятие с публикации — действие администратора, поэтому и решение о судьбе URL тоже: допустимы только 301 / 404 / 410.
     */
    mode?: ('301' | '410' | '404') | null;
    /**
     * Путь замены от корня сайта — только для 301. Абсолютный URL недопустим: хост собирается единственным хелпером из SITE_URL.
     */
    redirectTo?: string | null;
  };
  /**
   * URL опубликованной записи неизменяем. Чтобы перенести страницу, поставьте подтверждение и в том же сохранении измените slug (у подборки — slug, родителя или вид узла): 301 создастся автоматически, в той же транзакции. Цепочки редиректов при этом схлопываются, а не выстраиваются.
   */
  urlChange?: {
    /**
     * Подтверждаю смену URL: со старого пути будет создан одиночный 301. Одноразовое: после сохранения флаг снимается.
     */
    confirm?: boolean | null;
    /**
     * Причина переноса. Попадает в комментарий редиректа: через год именно он объясняет, почему адрес отдаёт 301.
     */
    reason?: string | null;
  };
  titleKey?: string | null;
  metaDescriptionKey?: string | null;
  /**
   * Совпадения title и meta description с другими страницами — по открыткам и подборкам сразу, в статусах published и review (ТЗ §8.3.1). Сохранение при совпадении проходит: это предупреждение. А перевод в review и дальше — только после правки текста или явного подтверждения.
   */
  metaConflict?: {
    /**
     * Заполняется хуком при каждом сохранении: чей текст совпал, по какому полю и по какому адресу лежит страница. Снаружи не пишется.
     */
    conflicts?:
      | {
          field?: ('title' | 'metaDescription') | null;
          documentCollection?: ('cards' | 'collections') | null;
          /**
           * Идентификатор конфликтующей записи строкой, а не связью: снимок обязан переживать удаление той записи — иначе исчезал бы след ровно того события, ради которого снимок и смотрят.
           */
          documentId?: string | null;
          path?: string | null;
          status?: string | null;
          title?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Сколько совпадений найдено ВСЕГО. Отдельно от длины списка: список ограничен, а по этому числу видно, что за ним стоит.
     */
    total?: number | null;
    /**
     * Список показан не полностью: найдено больше, чем помещается.
     */
    truncated?: boolean | null;
    /**
     * Когда снимок сделан. Снимок верен НА ЭТОТ МОМЕНТ: конфликтующую страницу с тех пор могли переименовать или удалить.
     */
    checkedAt?: string | null;
    /**
     * ОДНОРАЗОВОЕ подтверждение: «совпадение вижу, веду страницу дальше». Отметьте его в том же сохранении, которым переводите запись в review. Хук снимает флаг после сохранения, а само подтверждение действует только для ТОГО набора совпадений, который был на момент отметки: изменился текст или круг конфликтующих страниц — подтверждайте заново.
     */
    confirm?: boolean | null;
    /**
     * Отпечаток набора совпадений, для которого выдано подтверждение. Не совпал с текущим — подтверждение устарело, и переход снова заблокирован.
     */
    confirmedFor?: string | null;
    /**
     * Когда подтверждение выдано.
     */
    confirmedAt?: string | null;
    /**
     * Кто подтвердил совпадение. Записывается потому, что подтверждать вправе и сервисный аккаунт ai-editor (перевод draft → review — его штатное действие), а решение «две страницы с одинаковым заголовком допустимы» обязано быть прослеживаемым.
     */
    confirmedBy?: (number | null) | User;
    /**
     * Одной строкой по тому же снимку. Поле приходит в REST и GraphQL: правило, видимое только в форме админки, для внешнего клиента не существует.
     */
    summary?: string | null;
  };
  /**
   * Похожие открытки среди published и review (ТЗ §6.7 п. 4). Пока набор непуст, перевод в review заблокирован: решение принимает редактор, а порог похожести только подсказывает.
   */
  visualDuplicate?: {
    /**
     * Заполняется хуком при каждом сохранении: что нашлось по перцептивному хешу и на каком расстоянии Хэмминга. Снаружи не пишется.
     */
    similar?:
      | {
          card?: (number | null) | Card;
          distance?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Решение редактора о найденном наборе похожих. Только «уникально» открывает перевод в review; «это дубль» его закрывает — изображение нужно заменить.
     */
    decision?: ('unique' | 'duplicate') | null;
    /**
     * ОДНОРАЗОВОЕ подтверждение: отметьте его вместе с решением. Хук сбрасывает флаг после сохранения — иначе решение, принятое для прежней картинки, молча подтверждало бы и новую.
     */
    confirm?: boolean | null;
    /**
     * Отпечаток набора похожих, для которого выдано решение (хеш изображения плюс список найденных). Не совпал с текущим — решение устарело, и переход снова заблокирован.
     */
    decisionFor?: string | null;
    /**
     * Когда решение подтверждено.
     */
    decidedAt?: string | null;
    /**
     * Кто принял решение о похожих. Записывается потому, что принять его вправе и сервисный аккаунт ai-editor — перевод draft → review его штатное действие (ТЗ §9). DoD Э5-02 требует, чтобы решение было не только записано, но и прослеживаемо: без автора «уникально» у визуального дубля остаётся решением без ответственного.
     */
    decidedBy?: (number | null) | User;
    /**
     * Сколько записей просмотрено при последнем поиске похожих. Полнота проверки — часть её результата: без этого числа «похожих не найдено» невозможно отличить от «искали не везде».
     */
    scanned?: number | null;
    /**
     * Обход каталога оборвался по пределу — проверка НЕПОЛНАЯ, и пустой список похожих ничего не гарантирует. Отметка ставится хуком и попадает в журнал (находка ревизии от 2026-08-22: прежний предел 500 записей обрезал круг поиска молча).
     */
    scanTruncated?: boolean | null;
  };
  /**
   * Перцептивный хеш изображения. Считает @otkritka/images при загрузке (задача Э2-05); снаружи не пишется, иначе поиск визуальных дублей можно было бы обойти подстановкой чужого значения.
   */
  pHash?: string | null;
  /**
   * Зеркало связанной записи card-images: служебные поля постоянства URL файлов и сами производные (variants). Заполняются пайплайном изображений (Э2-05, Э2-06) и хуком карточки (Э3-03a), снаружи не пишутся ни через админку, ни через API.
   */
  derivative?: {
    /**
     * СОХРАНЁННЫЙ ключ производной (<префикс>/<revision>/<имя>), условие C1. Хранится, а не пересчитывается: сегодня ключ — функция от описания, лимита длины имени и таблицы транслитерации, поэтому правка заголовка или пополнение таблицы дали бы другой путь при том же содержимом. Фиксируется при первой публикации и далее неизменяем.
     */
    keyBase?: string | null;
    /**
     * Имя файла на транслите вместе с суффиксом уникальности, присвоенное при загрузке. Хранится отдельно от ключа, потому что при замене изображения меняется только revision, а имя остаётся тем же.
     */
    nameStem?: string | null;
    /**
     * Число N в суффиксе -N, уникализирующем имя файла (решение человека, блок 5 п. 3). Присваивается ОДИН раз при загрузке и хранится: если вычислять его заново, удаление ранней записи освободило бы N и путь другой записи изменился бы незаметно. После удаления N не переиспользуется.
     */
    nameSuffix?: number | null;
    /**
     * Короткий хеш байтов оригинала (решение Ч-28, вариант «а»). Меняется ТОЛЬКО при замене изображения — тогда меняются URL производных при неизменном URL карточки (ТЗ §6.7). Выводить revision из updatedAt или счётчика сохранений запрещено: каждое сохранение переписывало бы URL всех производных (условие C2).
     */
    revision?: string | null;
    /**
     * ЗЕРКАЛО card-images.variants[]: ключ, формат и ФАКТИЧЕСКИЕ размеры каждого файла. Из этого поля публичный рендер собирает src, srcset (дескриптор w), width и height — из одного значения (условие C8). Зеркало нужно потому, что коллекция card-images анонимно не читается, а публичный рендер читает как аноним и на depth 0: связь пришла бы идентификатором. Заполняется хуком при каждом сохранении карточки и пересинхронизируется при замене байтов изображения; снаружи не пишется никем — ни admin, ни ai-editor, ни через REST/GraphQL.
     */
    variants?:
      | {
          /**
           * Ключ объекта в хранилище. Публичный путь собирается из него единственной функцией derivativePublicPath (/media/<ключ>); хост добавляет хелпер над SITE_URL. Ключ содержит revision, поэтому постоянен (ТЗ §6.3, Ч-28).
           */
          key: string;
          /**
           * Формат вывода. Набор закрыт набором вывода пайплайна.
           */
          format: 'avif' | 'webp' | 'jpeg';
          /**
           * ФАКТИЧЕСКАЯ ширина готового файла из его метаданных. Отсюда берутся и дескриптор w в srcset, и атрибут width — из одного значения (условие C8). Запрошенная ширина (targetWidth) для этого не годится: на пропорциях, не делящихся нацело, она расходится с фактической, и место резервировалось бы не под ту картинку.
           */
          width: number;
          /**
           * ФАКТИЧЕСКАЯ высота готового файла. Атрибут height берётся отсюда: без пары width/height браузер не резервирует место, и загрузка изображения даёт CLS.
           */
          height: number;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Файлы открыток. При загрузке считаются производные AVIF/WebP/JPEG и перцептивный хеш; оригинал сохраняется вне публичного пространства. Имя файла и его URL постоянны: правка названия их не меняет. Удалить изображение можно только после того, как на него не ссылается ни одна карточка: иначе у карточки остались бы сохранённые адреса файлов, которых уже нет.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "card-images".
 */
export interface CardImage {
  id: number;
  /**
   * Описательное название изображения — из него один раз строится ИМЯ ФАЙЛА на транслите (например «Открытка маме на 8 марта с тюльпанами» → otkrytka-mame-na-8-marta-s-tyulpanami). После первой загрузки правка этого поля имя файла и пути производных НЕ меняет: URL файла постоянен (ТЗ §6.3).
   */
  title: string;
  /**
   * Перцептивный хеш изображения (@otkritka/images). Снаружи не пишется: иначе поиск визуальных дублей обходился бы подстановкой чужого значения.
   */
  pHash?: string | null;
  /**
   * Имя файла на транслите вместе с суффиксом -N, занятое ОДИН раз при загрузке (реестр image-name-claims). При замене изображения остаётся прежним — меняется только revision.
   */
  nameStem?: string | null;
  /**
   * Число N в суффиксе -N. Пусто у первого имени. После удаления записи номер не переиспользуется: реестр занятых имён строк не теряет.
   */
  nameSuffix?: number | null;
  /**
   * Короткий хеш БАЙТОВ оригинала (Ч-28). Меняется только при замене изображения — тогда меняются URL всех производных при неизменном URL карточки (ТЗ §6.7). Сохранение записи ревизию не трогает (условие C2).
   */
  revision?: string | null;
  /**
   * Общая часть ключей производных: <префикс>/<revision>/<имя>. Хранится, а не пересчитывается (условие C1).
   */
  keyBase?: string | null;
  /**
   * Непредсказуемый идентификатор оригинала (128 бит). Читается только админом: публиковать его незачем, а оригинал по нему не отдаётся вовсе.
   */
  storageId?: string | null;
  /**
   * Ключ оригинала в НЕПУБЛИЧНОМ пространстве хранилища. Из публичного пути производной не выводится и по HTTP не отдаётся.
   */
  originalKey?: string | null;
  /**
   * Производные: ключ, формат и ФАКТИЧЕСКИЕ размеры каждого файла. ИСТОЧНИК зеркала в карточке (cards.derivative.variants): публичный рендер читает как аноним, а эта коллекция анонимно не читается, поэтому те же четыре поля хук переносит в карточку. Формы полей общие с зеркалом (imageVariantFields), чтобы им нельзя было разъехаться: и путь, и дескриптор w в srcset, и атрибуты width/height берутся из одного места (условие C8), а не пересчитываются из настроек.
   */
  variants?:
    | {
        /**
         * Ключ объекта в хранилище. Публичный путь собирается из него единственной функцией derivativePublicPath (/media/<ключ>); хост добавляет хелпер над SITE_URL. Ключ содержит revision, поэтому постоянен (ТЗ §6.3, Ч-28).
         */
        key: string;
        /**
         * Формат вывода. Набор закрыт набором вывода пайплайна.
         */
        format: 'avif' | 'webp' | 'jpeg';
        /**
         * ФАКТИЧЕСКАЯ ширина готового файла из его метаданных. Отсюда берутся и дескриптор w в srcset, и атрибут width — из одного значения (условие C8). Запрошенная ширина (targetWidth) для этого не годится: на пропорциях, не делящихся нацело, она расходится с фактической, и место резервировалось бы не под ту картинку.
         */
        width: number;
        /**
         * ФАКТИЧЕСКАЯ высота готового файла. Атрибут height берётся отсюда: без пары width/height браузер не резервирует место, и загрузка изображения даёт CLS.
         */
        height: number;
        /**
         * Размер файла в байтах. В зеркало карточки НЕ переносится: разметка его не использует.
         */
        byteSize: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Что было на входе, по метаданным: размеры ПОСЛЕ применения EXIF Orientation и значение самого тега. Нужны для разбора «почему производных меньше, чем ширин».
   */
  source?: {
    width?: number | null;
    height?: number | null;
    format?: string | null;
    exifOrientation?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Подборки и посадочные. URL собирается из цепочки родителей: /podborki/<группа>/<повод>/<уточнение>. Порядок только «повод → уточнение». Новая запись — draft с noindex; публикует и открывает в индекс только человек.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  /**
   * Заголовок страницы (title). Уникален в пределах каталога — совпадения проверяются при сохранении (задача Э5-01). Смена заголовка URL не меняет.
   */
  title: string;
  /**
   * H1 страницы. Пустой — совпадает с title (ТЗ §8.1).
   */
  h1?: string | null;
  /**
   * Один сегмент URL. Итоговый путь собирается из пути родителя и этого сегмента, например /podborki/prazdniki/8-marta/mame. Slug праздника с фиксированной датой — <число>-<месяц> (8-marta, 9-maya); без фиксированной даты — короткое название (paskha, novyy-god), решение Ч-04-4. Год в URL ежегодного праздника не добавляется. Неизменяем после первой публикации (смена — только вместе с одиночным 301, задача Э1-09).
   */
  slug: string;
  /**
   * ИТОГОВЫЙ путь подборки. Считается хуком из цепочки родителей и хранится с уникальным индексом БД: уникальность URL не может держаться на проверке запросом перед записью — два одновременных сохранения через API прошли бы её оба. Снаружи не пишется ни через админку, ни через API.
   */
  path?: string | null;
  /**
   * Определяет, куда узел можно вложить: группа — только в корень /podborki, повод — под группу, уточнение — под группу или под повод. Порядок только «повод → уточнение» (решение Ч-04-7): праздник под адресатом не создаётся никогда. Вида под стиль и настроение нет намеренно — по решению Ч-04-3 это фильтр без собственных URL.
   */
  nodeKind: 'group' | 'occasion' | 'recipient';
  /**
   * Родительский узел. Пусто — узел верхнего уровня (прямо под /podborki). Смена родителя меняет URL этой подборки и всех вложенных, поэтому после первой публикации она возможна только вместе с одиночным 301 (задача Э1-09).
   */
  parent?: (number | null) | Collection;
  /**
   * Вводный текст страницы (ТЗ §8.1). Должен быть уникальным и осмысленным: шаблонный текст с заменой пары слов — прямой запрет п. 23 SEO ТЗ, а уникальность вводного текста входит в условия открытия страницы в index,follow (п. 5.1). Набор возможностей редактора сужен до того, что печатает публичный шаблон: изображения, ссылки-записи, разделители и выравнивание недоступны намеренно — они исчезали бы на странице молча. Ссылка внутрь сайта задаётся путём от корня, например /podborki/prazdniki/8-marta.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Meta description. Совпадения по каталогу проверяются при сохранении (задача Э5-01). index,follow не применяется, пока пусто meta description: страница без непустого описания понижается до noindex,follow и не попадает в sitemap. Поэтому сохранение с index,follow и пустым описанием отклоняется — иначе решение осталось бы в поле и не действовало на сайте.
   */
  metaDescription?: string | null;
  /**
   * draft → review → published. Перевод в published — осознанное действие человека с ролью admin; сервисный аккаунт ai-editor доводит запись до review.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * index,follow — только для published и только по решению администратора при выполнении условий п. 5.1 SEO ТЗ (подтверждённый спрос, отдельный интент, достаточный объём, уникальные тексты, страница в навигации). index,follow не применяется, пока пусто meta description: страница без непустого описания понижается до noindex,follow и не попадает в sitemap. Поэтому сохранение с index,follow и пустым описанием отклоняется — иначе решение осталось бы в поле и не действовало на сайте.
   */
  robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
  /**
   * Пусто = self-canonical (норма). Переопределение — только администратор и только путём от корня: абсолютный URL собирается из SITE_URL, вручную его вписывать нельзя.
   */
  canonical?: string | null;
  /**
   * Дата первой публикации. Ставится автоматически при первом переводе в published (Э1-08) и далее не меняется: по ней определяется, что URL уже был известен поисковику.
   */
  publishedAt?: string | null;
  /**
   * Меняется ТОЛЬКО при содержательном обновлении: это lastmod в sitemap. Техническая правка (опечатка, служебное поле) дату не двигает — иначе lastmod перестаёт что-либо означать для поисковика.
   */
  updatedContentAt?: string | null;
  /**
   * Заполняется при переводе опубликованной записи в draft или review. Без решения снятие с публикации отклоняется: этот URL уже известен поисковику, и молчаливое исчезновение страницы — это либо потерянный вес ссылки, либо мягкий 404.
   */
  withdrawal?: {
    /**
     * Снятие с публикации — действие администратора, поэтому и решение о судьбе URL тоже: допустимы только 301 / 404 / 410.
     */
    mode?: ('301' | '410' | '404') | null;
    /**
     * Путь замены от корня сайта — только для 301. Абсолютный URL недопустим: хост собирается единственным хелпером из SITE_URL.
     */
    redirectTo?: string | null;
  };
  /**
   * URL опубликованной записи неизменяем. Чтобы перенести страницу, поставьте подтверждение и в том же сохранении измените slug (у подборки — slug, родителя или вид узла): 301 создастся автоматически, в той же транзакции. Цепочки редиректов при этом схлопываются, а не выстраиваются.
   */
  urlChange?: {
    /**
     * Подтверждаю смену URL: со старого пути будет создан одиночный 301. Одноразовое: после сохранения флаг снимается.
     */
    confirm?: boolean | null;
    /**
     * Причина переноса. Попадает в комментарий редиректа: через год именно он объясняет, почему адрес отдаёт 301.
     */
    reason?: string | null;
  };
  titleKey?: string | null;
  metaDescriptionKey?: string | null;
  /**
   * Совпадения title и meta description с другими страницами — по открыткам и подборкам сразу, в статусах published и review (ТЗ §8.3.1). Сохранение при совпадении проходит: это предупреждение. А перевод в review и дальше — только после правки текста или явного подтверждения.
   */
  metaConflict?: {
    /**
     * Заполняется хуком при каждом сохранении: чей текст совпал, по какому полю и по какому адресу лежит страница. Снаружи не пишется.
     */
    conflicts?:
      | {
          field?: ('title' | 'metaDescription') | null;
          documentCollection?: ('cards' | 'collections') | null;
          /**
           * Идентификатор конфликтующей записи строкой, а не связью: снимок обязан переживать удаление той записи — иначе исчезал бы след ровно того события, ради которого снимок и смотрят.
           */
          documentId?: string | null;
          path?: string | null;
          status?: string | null;
          title?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Сколько совпадений найдено ВСЕГО. Отдельно от длины списка: список ограничен, а по этому числу видно, что за ним стоит.
     */
    total?: number | null;
    /**
     * Список показан не полностью: найдено больше, чем помещается.
     */
    truncated?: boolean | null;
    /**
     * Когда снимок сделан. Снимок верен НА ЭТОТ МОМЕНТ: конфликтующую страницу с тех пор могли переименовать или удалить.
     */
    checkedAt?: string | null;
    /**
     * ОДНОРАЗОВОЕ подтверждение: «совпадение вижу, веду страницу дальше». Отметьте его в том же сохранении, которым переводите запись в review. Хук снимает флаг после сохранения, а само подтверждение действует только для ТОГО набора совпадений, который был на момент отметки: изменился текст или круг конфликтующих страниц — подтверждайте заново.
     */
    confirm?: boolean | null;
    /**
     * Отпечаток набора совпадений, для которого выдано подтверждение. Не совпал с текущим — подтверждение устарело, и переход снова заблокирован.
     */
    confirmedFor?: string | null;
    /**
     * Когда подтверждение выдано.
     */
    confirmedAt?: string | null;
    /**
     * Кто подтвердил совпадение. Записывается потому, что подтверждать вправе и сервисный аккаунт ai-editor (перевод draft → review — его штатное действие), а решение «две страницы с одинаковым заголовком допустимы» обязано быть прослеживаемым.
     */
    confirmedBy?: (number | null) | User;
    /**
     * Одной строкой по тому же снимку. Поле приходит в REST и GraphQL: правило, видимое только в форме админки, для внешнего клиента не существует.
     */
    summary?: string | null;
  };
  /**
   * Ответственный редактор подборки. По умолчанию — администратор (решение Ч-16): даже если запись создал сервисный аккаунт ai-editor, ответственным остаётся человек, потому что решение о публикации принимает он.
   */
  responsibleEditor?: (number | null) | User;
  /**
   * Смежные подборки (m:n, ТЗ §8.1). Из них строится перелинковка: она же закрывает требование «нет страниц-сирот» — каждая индексируемая страница достижима за ≤ 4 перехода от главной.
   */
  related?: (number | Collection)[] | null;
  /**
   * Календарь праздников — официальный календарь РФ, даты вводятся здесь (решение Ч-12). Дата готовности по умолчанию — за 45 дней до праздника; окно ТЗ §8.6 — 4–8 недель.
   */
  seasonal?: {
    /**
     * Дата праздника по официальному календарю РФ. Списка праздников в коде нет намеренно: он разошёлся бы с календарём при первом переносе выходных, а обновлять его пришлось бы деплоем.
     */
    holidayDate?: string | null;
    /**
     * Дата готовности. Пусто — ставится автоматически за 45 дней до праздника (Ч-12); заданное значение не перезаписывается.
     */
    readyBy?: string | null;
    /**
     * С какого дня подборка показывается в сезонном блоке главной (ТЗ §8.1). Даты показа переключают БЛОК на главной и не создают отдельных URL.
     */
    showFrom?: string | null;
    /**
     * По какой день подборка показывается в сезонном блоке главной.
     */
    showUntil?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Две роли: admin (человек, полные права) и ai-editor (сервисный аккаунт с API-ключом, доводит контент до review).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * admin — полные права, включая публикацию и index,follow. ai-editor — черновики, метаданные, привязка к подборкам и перевод draft → review. Значения по умолчанию нет: роль указывается явно при создании пользователя.
   */
  role: 'admin' | 'ai-editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Одиночные 301 и 410. Цепочки запрещены: новый редирект, создающий цепочку, схлопывается автоматически, а петля отклоняется.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Старый путь от корня сайта, например /otkrytki/staraya-otkrytka. Уникален: два правила для одного пути сделали бы ответ зависимым от порядка строк. Маршрут, который сайт обслуживает сам, источником быть не может: «/», «/otkrytki», «/podborki», «/search», «/account», служебные страницы, файлы robots и sitemap, «/media», путь админки и любой путь под ними — редирект оттуда сделал бы живую страницу недостижимой. Адреса записей под каталогами переносить можно.
   */
  from: string;
  /**
   * Новый путь от корня сайта. Обязателен для 301 и обязан быть ПУСТЫМ для 410. Абсолютный URL недопустим: хост собирается из SITE_URL. В отличие от поля «from», цель МОЖЕТ быть служебным маршрутом — каталогом, информационной страницей или главной: цель редиректа обязана быть достижимой, и запрет здесь сделал бы часть переносов невыполнимой.
   */
  to?: string | null;
  /**
   * Только 301 и 410. Временных редиректов в модели нет: перенос страницы — постоянное решение, а 302 не передаёт сигналы старого URL новому.
   */
  code: '301' | '410';
  /**
   * Кто создал правило: заполняется сервером и не приходит из запроса.
   */
  createdBy?: (number | null) | User;
  /**
   * Зачем создан редирект: причина переноса, ссылка на задачу.
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Журнал изменений SEO-полей: что, когда, кем (человек или сервисный аккаунт), старое → новое. Заполняется хуками автоматически, вручную не редактируется.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-history".
 */
export interface SeoHistory {
  id: number;
  /**
   * Коллекция изменённой записи.
   */
  documentCollection: 'cards' | 'collections';
  /**
   * Идентификатор записи. Строкой, а не связью: история обязана переживать удаление документа — иначе исчезал бы след ровно того события, из-за которого чаще всего и смотрят журнал.
   */
  documentId: string;
  /**
   * Путь записи на момент изменения. Хранится копией: по нему история читается как список URL, а не как список идентификаторов.
   */
  documentPath?: string | null;
  /**
   * Какое SEO-поле изменилось.
   */
  field: 'title' | 'h1' | 'metaDescription' | 'slug' | 'path' | 'canonical' | 'robots' | 'status';
  /**
   * Значение ДО изменения. Пусто — поле не было заполнено.
   */
  previousValue?: string | null;
  /**
   * Значение ПОСЛЕ изменения.
   */
  nextValue?: string | null;
  /**
   * Операция, в которой произошло изменение.
   */
  operation: 'create' | 'update';
  /**
   * Кто изменил: admin (человек), ai-editor (сервисный аккаунт), system (операция без пользователя — миграция, скрипт) или unknown (роль не распознана — это инцидент, а не норма).
   */
  authorRole: 'admin' | 'ai-editor' | 'system' | 'unknown';
  /**
   * Аккаунт автора изменения. Пусто — операция без пользователя.
   */
  changedBy?: (number | null) | User;
  /**
   * Изменение пришло по API-ключу (ТЗ §9). Признак хранится отдельно от роли: один и тот же аккаунт может работать и через админку, и через API.
   */
  viaApiKey?: boolean | null;
  /**
   * Момент изменения. Ставится хуком; собственное поле, а не createdAt, чтобы все записи одной операции имели ровно одно время.
   */
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Служебный реестр: имена файлов изображений, которые когда-либо были выданы. Строки не удаляются — иначе номер -N достался бы другому изображению, и путь, уже известный поисковику, указывал бы на другой файл.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-name-claims".
 */
export interface ImageNameClaim {
  id: number;
  /**
   * Имя файла без расширения вместе с суффиксом (например otkrytka-mame-2). Уникальность держит индекс базы: гонка двух загрузок иначе выдала бы один путь.
   */
  stem: string;
  /**
   * Число N в суффиксе -N. Пусто у первого имени: у него суффикса нет вовсе, иначе у одного изображения было бы два законных пути («имя» и «имя-1»).
   */
  suffix?: number | null;
  /**
   * Описание, из которого имя построено. Нужно для разбора «почему -N».
   */
  description?: string | null;
  /**
   * Когда имя занято.
   */
  claimedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cards';
        value: number | Card;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'card-images';
        value: number | CardImage;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'seo-history';
        value: number | SeoHistory;
      } | null)
    | ({
        relationTo: 'image-name-claims';
        value: number | ImageNameClaim;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards_select".
 */
export interface CardsSelect<T extends boolean = true> {
  title?: T;
  h1?: T;
  slug?: T;
  image?: T;
  alt?: T;
  caption?: T;
  description?: T;
  metaDescription?: T;
  usageTerms?: T;
  collections?: T;
  status?: T;
  robots?: T;
  canonical?: T;
  publishedAt?: T;
  updatedContentAt?: T;
  withdrawal?:
    | T
    | {
        mode?: T;
        redirectTo?: T;
      };
  urlChange?:
    | T
    | {
        confirm?: T;
        reason?: T;
      };
  titleKey?: T;
  metaDescriptionKey?: T;
  metaConflict?:
    | T
    | {
        conflicts?:
          | T
          | {
              field?: T;
              documentCollection?: T;
              documentId?: T;
              path?: T;
              status?: T;
              title?: T;
              id?: T;
            };
        total?: T;
        truncated?: T;
        checkedAt?: T;
        confirm?: T;
        confirmedFor?: T;
        confirmedAt?: T;
        confirmedBy?: T;
        summary?: T;
      };
  visualDuplicate?:
    | T
    | {
        similar?:
          | T
          | {
              card?: T;
              distance?: T;
              id?: T;
            };
        decision?: T;
        confirm?: T;
        decisionFor?: T;
        decidedAt?: T;
        decidedBy?: T;
        scanned?: T;
        scanTruncated?: T;
      };
  pHash?: T;
  derivative?:
    | T
    | {
        keyBase?: T;
        nameStem?: T;
        nameSuffix?: T;
        revision?: T;
        variants?:
          | T
          | {
              key?: T;
              format?: T;
              width?: T;
              height?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  h1?: T;
  slug?: T;
  path?: T;
  nodeKind?: T;
  parent?: T;
  intro?: T;
  metaDescription?: T;
  status?: T;
  robots?: T;
  canonical?: T;
  publishedAt?: T;
  updatedContentAt?: T;
  withdrawal?:
    | T
    | {
        mode?: T;
        redirectTo?: T;
      };
  urlChange?:
    | T
    | {
        confirm?: T;
        reason?: T;
      };
  titleKey?: T;
  metaDescriptionKey?: T;
  metaConflict?:
    | T
    | {
        conflicts?:
          | T
          | {
              field?: T;
              documentCollection?: T;
              documentId?: T;
              path?: T;
              status?: T;
              title?: T;
              id?: T;
            };
        total?: T;
        truncated?: T;
        checkedAt?: T;
        confirm?: T;
        confirmedFor?: T;
        confirmedAt?: T;
        confirmedBy?: T;
        summary?: T;
      };
  responsibleEditor?: T;
  related?: T;
  seasonal?:
    | T
    | {
        holidayDate?: T;
        readyBy?: T;
        showFrom?: T;
        showUntil?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "card-images_select".
 */
export interface CardImagesSelect<T extends boolean = true> {
  title?: T;
  pHash?: T;
  nameStem?: T;
  nameSuffix?: T;
  revision?: T;
  keyBase?: T;
  storageId?: T;
  originalKey?: T;
  variants?:
    | T
    | {
        key?: T;
        format?: T;
        width?: T;
        height?: T;
        byteSize?: T;
        id?: T;
      };
  source?:
    | T
    | {
        width?: T;
        height?: T;
        format?: T;
        exifOrientation?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  code?: T;
  createdBy?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-history_select".
 */
export interface SeoHistorySelect<T extends boolean = true> {
  documentCollection?: T;
  documentId?: T;
  documentPath?: T;
  field?: T;
  previousValue?: T;
  nextValue?: T;
  operation?: T;
  authorRole?: T;
  changedBy?: T;
  viaApiKey?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-name-claims_select".
 */
export interface ImageNameClaimsSelect<T extends boolean = true> {
  stem?: T;
  suffix?: T;
  description?: T;
  claimedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Значения, которые решениями человека вынесены из кода в админку: данные организации (Ч-17), лицензия изображений (Ч-10), тексты служебных страниц (Ч-19), рекламные места (Ч-11). Все поля пустые по умолчанию, и пустое поле — это не «ещё не дошли руки», а команда шаблону промолчать: блока разметки нет, страница остаётся noindex, рекламное место не выводится.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Данные для разметки Organization на главной (решение Ч-17). Пока не заполнены name и logo, блок Organization не выводится ВОВСЕ — разметка с пустыми или придуманными значениями запрещена п. 23 ТЗ. Остальные поля попадают в разметку по одному, по факту заполнения.
   */
  organization?: {
    /**
     * Название проекта так, как оно видно на сайте. Разметка обязана совпадать с видимым содержимым, поэтому здесь не «красивое» имя, а то же самое.
     */
    name?: string | null;
    /**
     * Юридическое наименование, если оно есть и отличается от бренда. Пусто — свойства legalName в разметке не будет.
     */
    legalName?: string | null;
    /**
     * Путь к файлу логотипа от корня сайта, например /media/site/logo.svg. Абсолютный адрес недопустим: хост подставляет единственный хелпер из SITE_URL. Без логотипа блок Organization не выводится.
     */
    logo?: string | null;
    /**
     * Контактный адрес. Пусто — свойства email в разметке не будет.
     */
    email?: string | null;
    /**
     * Контактный телефон. Пусто — свойства telephone в разметке не будет.
     */
    telephone?: string | null;
    /**
     * Ссылки на официальные профили проекта. Здесь — и только здесь — адрес полный: профиль живёт на чужом хосте, и правило «хост только из SITE_URL» к нему не относится.
     */
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Лицензионные свойства ImageObject (решение Ч-10). Набор проверяется ЦЕЛИКОМ: пока не заполнены все поля набора (creator, creditText, copyrightNotice, license, acquireLicensePage), лицензионная часть разметки не выводится. Частично заполненная лицензия хуже отсутствующей — она выглядит юридически значимой, не будучи ею, а правится потом сразу на всём массиве опубликованных карточек.
   */
  imageLicense?: {
    /**
     * Кто создал изображение (свойство creator). Фиктивный автор запрещён п. 23 ТЗ: изображения генерирует нейросеть, и указание должно быть правдивым. Рядом обязателен ВИД правообладателя: без него свойство не выводится.
     */
    creator?: string | null;
    /**
     * Организация или человек. Выбор обязателен при заполненном имени, и значения по умолчанию у него нет намеренно: диапазон свойства creator в schema.org — Person или Organization, то есть УЗЕЛ со своим типом, а строка без типа для потребителя разметки равна отсутствию свойства. Догадаться о виде по имени нельзя — различие юридическое, а не стилистическое, поэтому его выбирает человек. Пока не выбран, лицензионный блок разметки не выводится вовсе (набор Ч-10 проверяется целиком).
     */
    creatorKind?: ('Organization' | 'Person') | null;
    /**
     * Строка указания источника (creditText).
     */
    creditText?: string | null;
    /**
     * Уведомление об авторских правах (copyrightNotice).
     */
    copyrightNotice?: string | null;
    /**
     * Путь к странице лицензии от корня сайта — по решению Ч-10 это /usloviya. Абсолютный адрес недопустим: хост подставляет единственный хелпер из SITE_URL.
     */
    license?: string | null;
    /**
     * Путь к странице, где можно получить лицензию — по решению Ч-10 это /usloviya. Ссылка отсюда работает и на неиндексируемой странице, поэтому доводом за её индексацию не является (Ч-23).
     */
    acquireLicensePage?: string | null;
    /**
     * Формулировка указания на то, что изображение создано нейросетью (решение Ч-10). Выводится ВИДИМОЙ подписью на карточке, а не свойством разметки: свойства с таким смыслом в schema.org нет, а придумывать его нельзя — разметка обязана соответствовать видимому содержимому. Полная формулировка живёт в «Условиях использования» (/usloviya).
     */
    aiDisclosure?: string | null;
  };
  /**
   * Тексты трёх страниц (решение Ч-19). Сами страницы — статические маршруты Astro, а не записи CMS: отдельной коллекции `pages` в модели данных нет, и реестр зарезервированных маршрутов запрещает запись CMS с таким путём. Здесь содержимое, которое правит человек, и его же решение об индексации каждой страницы.
   */
  infoPages?: {
    /**
     * Тексты страницы /o-proekte и решение об её индексации. В index,follow и в sitemap страница попадает только при ДВУХ условиях сразу: ниже включён выключатель «Открыть в index,follow» И страница наполнена (минимум 400 символов в теле плюс заполненные title и description). Иначе — noindex и вне sitemap, таково условие решения Ч-23. Текст-заглушка на индексируемой странице запрещён п. 23 ТЗ.
     */
    about?: {
      /**
       * Включает индексацию страницы (решение Ч-23). По умолчанию выключен: дефолт закрывающий, страница не уходит в индекс сама. Включение — осознанное действие человека с ролью admin (п. 7.1 и п. 23 ТЗ), автоматике оно недоступно. Одного включения мало: пока страница не наполнена, она остаётся noindex — выключатель не отменяет требований п. 5.1 к полноценной странице.
       */
      allowIndexing?: boolean | null;
      /**
       * Заголовок страницы (title). Обязан быть уникальным на выборке приёмки.
       */
      title?: string | null;
      /**
       * H1 страницы. Пусто — совпадает с title: то же правило, что у контентных коллекций (ТЗ §8.1), поэтому H1 не входит в условия индексации.
       */
      h1?: string | null;
      /**
       * Description страницы. Обязателен для индексации (Ч-23).
       */
      metaDescription?: string | null;
      /**
       * Основной текст. Присутствует в HTML-ответе сервера — страница обязана быть полноценной при отключённом JS. Набор возможностей редактора сужен до того, что печатает публичный шаблон: изображения, ссылки-записи, разделители и выравнивание недоступны намеренно. Ссылка внутрь сайта задаётся путём от корня (например /usloviya), внешняя — полным адресом по http или https; mailto: и tel: шаблон ссылкой не печатает, поэтому и сохранить их нельзя.
       */
      body?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Вычисляется при каждом чтении по тому же правилу Ч-23, по которому директиву считает публичный шаблон. Поле только для чтения и приходит в REST и GraphQL: иначе состояние индексации было бы известно лишь форме админки.
       */
      indexationState?: string | null;
    };
    /**
     * Тексты страницы /usloviya и решение об её индексации. В index,follow и в sitemap страница попадает только при ДВУХ условиях сразу: ниже включён выключатель «Открыть в index,follow» И страница наполнена (минимум 400 символов в теле плюс заполненные title и description). Иначе — noindex и вне sitemap, таково условие решения Ч-23. Текст-заглушка на индексируемой странице запрещён п. 23 ТЗ.
     */
    terms?: {
      /**
       * Включает индексацию страницы (решение Ч-23). По умолчанию выключен: дефолт закрывающий, страница не уходит в индекс сама. Включение — осознанное действие человека с ролью admin (п. 7.1 и п. 23 ТЗ), автоматике оно недоступно. Одного включения мало: пока страница не наполнена, она остаётся noindex — выключатель не отменяет требований п. 5.1 к полноценной странице.
       */
      allowIndexing?: boolean | null;
      /**
       * Заголовок страницы (title). Обязан быть уникальным на выборке приёмки.
       */
      title?: string | null;
      /**
       * H1 страницы. Пусто — совпадает с title: то же правило, что у контентных коллекций (ТЗ §8.1), поэтому H1 не входит в условия индексации.
       */
      h1?: string | null;
      /**
       * Description страницы. Обязателен для индексации (Ч-23).
       */
      metaDescription?: string | null;
      /**
       * Основной текст. Присутствует в HTML-ответе сервера — страница обязана быть полноценной при отключённом JS. Набор возможностей редактора сужен до того, что печатает публичный шаблон: изображения, ссылки-записи, разделители и выравнивание недоступны намеренно. Ссылка внутрь сайта задаётся путём от корня (например /usloviya), внешняя — полным адресом по http или https; mailto: и tel: шаблон ссылкой не печатает, поэтому и сохранить их нельзя.
       */
      body?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Вычисляется при каждом чтении по тому же правилу Ч-23, по которому директиву считает публичный шаблон. Поле только для чтения и приходит в REST и GraphQL: иначе состояние индексации было бы известно лишь форме админки.
       */
      indexationState?: string | null;
    };
    /**
     * Тексты страницы /kontakty и решение об её индексации. В index,follow и в sitemap страница попадает только при ДВУХ условиях сразу: ниже включён выключатель «Открыть в index,follow» И страница наполнена (минимум 400 символов в теле плюс заполненные title и description). Иначе — noindex и вне sitemap, таково условие решения Ч-23. Текст-заглушка на индексируемой странице запрещён п. 23 ТЗ.
     */
    contacts?: {
      /**
       * Включает индексацию страницы (решение Ч-23). По умолчанию выключен: дефолт закрывающий, страница не уходит в индекс сама. Включение — осознанное действие человека с ролью admin (п. 7.1 и п. 23 ТЗ), автоматике оно недоступно. Одного включения мало: пока страница не наполнена, она остаётся noindex — выключатель не отменяет требований п. 5.1 к полноценной странице.
       */
      allowIndexing?: boolean | null;
      /**
       * Заголовок страницы (title). Обязан быть уникальным на выборке приёмки.
       */
      title?: string | null;
      /**
       * H1 страницы. Пусто — совпадает с title: то же правило, что у контентных коллекций (ТЗ §8.1), поэтому H1 не входит в условия индексации.
       */
      h1?: string | null;
      /**
       * Description страницы. Обязателен для индексации (Ч-23).
       */
      metaDescription?: string | null;
      /**
       * Основной текст. Присутствует в HTML-ответе сервера — страница обязана быть полноценной при отключённом JS. Набор возможностей редактора сужен до того, что печатает публичный шаблон: изображения, ссылки-записи, разделители и выравнивание недоступны намеренно. Ссылка внутрь сайта задаётся путём от корня (например /usloviya), внешняя — полным адресом по http или https; mailto: и tel: шаблон ссылкой не печатает, поэтому и сохранить их нельзя.
       */
      body?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Вычисляется при каждом чтении по тому же правилу Ч-23, по которому директиву считает публичный шаблон. Поле только для чтения и приходит в REST и GraphQL: иначе состояние индексации было бы известно лишь форме админки.
       */
      indexationState?: string | null;
    };
  };
  /**
   * Два ряда по три блока (решение Ч-11): под H1 над сеткой и после пагинации. Место резервируется по ЭТИМ размерам, поэтому блок без ширины и высоты не выводится вовсе: нулевой контейнер даёт ровно тот сдвиг макета, против которого резервирование и существует (CLS < 0,1). Порядок блоков внутри ряда — порядок строк здесь.
   */
  adSlots?:
    | {
        /**
         * Ряд, в котором стоит блок. Набор закрыт решением Ч-11: произвольная позиция означала бы блок, который шаблон не выведет нигде.
         */
        position: 'under-h1' | 'after-pagination';
        /**
         * Ширина блока в пикселях — точное значение из кабинета рекламной сети. Пусто — блок не выводится.
         */
        width?: number | null;
        /**
         * Высота блока в пикселях. Соотношение сторон отдельным полем не задаётся: резервировать место можно только по конкретным числам, а из двух размеров соотношение выводится, обратное — нет.
         */
        height?: number | null;
        /**
         * Выводить блок. По умолчанию выключен: дефолт закрывающий — реклама не появляется на странице сама.
         */
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Заполняется сервером при каждом сохранении и снаружи не пишется. Вместе с историей версий даёт полный след: версия хранит значения, эти поля — автора и время. Публично не отдаётся: настройки — открытые данные, а кто их менял — внутренняя кухня.
   */
  audit?: {
    /**
     * Момент последнего сохранения настроек.
     */
    changedAt?: string | null;
    /**
     * Роль автора. Здесь ожидается admin: запись в глобал доступна только человеку. Значение system означает операцию без пользователя (скрипт, миграция), unknown — нераспознанную роль, то есть инцидент.
     */
    authorRole?: ('admin' | 'ai-editor' | 'system' | 'unknown') | null;
    /**
     * Аккаунт автора. Пусто — операция без пользователя.
     */
    changedBy?: (number | null) | User;
    /**
     * Сохранение пришло по API-ключу (ТЗ §9). Признак отдельно от роли: один аккаунт может работать и через админку, и через API.
     */
    viaApiKey?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organization?:
    | T
    | {
        name?: T;
        legalName?: T;
        logo?: T;
        email?: T;
        telephone?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  imageLicense?:
    | T
    | {
        creator?: T;
        creatorKind?: T;
        creditText?: T;
        copyrightNotice?: T;
        license?: T;
        acquireLicensePage?: T;
        aiDisclosure?: T;
      };
  infoPages?:
    | T
    | {
        about?:
          | T
          | {
              allowIndexing?: T;
              title?: T;
              h1?: T;
              metaDescription?: T;
              body?: T;
              indexationState?: T;
            };
        terms?:
          | T
          | {
              allowIndexing?: T;
              title?: T;
              h1?: T;
              metaDescription?: T;
              body?: T;
              indexationState?: T;
            };
        contacts?:
          | T
          | {
              allowIndexing?: T;
              title?: T;
              h1?: T;
              metaDescription?: T;
              body?: T;
              indexationState?: T;
            };
      };
  adSlots?:
    | T
    | {
        position?: T;
        width?: T;
        height?: T;
        enabled?: T;
        id?: T;
      };
  audit?:
    | T
    | {
        changedAt?: T;
        authorRole?: T;
        changedBy?: T;
        viaApiKey?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}