/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    cards: Card;
    collections: Collection;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    cards: CardsSelect<false> | CardsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Карточка открытки. URL — /otkrytki/<slug>, один навсегда. Новая запись создаётся в draft с noindex; публикует и открывает в индекс только человек.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards".
 */
export interface Card {
  id: number;
  /**
   * Заголовок страницы (title). Уникален в пределах каталога — совпадения проверяются при сохранении (задача Э5-01). Смена заголовка URL не меняет.
   */
  title: string;
  /**
   * H1 страницы. Пустой — совпадает с title (ТЗ §8.1).
   */
  h1?: string | null;
  /**
   * URL записи: /otkrytki/<slug>. Неизменяем после первой публикации (смена возможна только вместе с одиночным 301 — задача Э1-09). Смена заголовка URL не меняет.
   */
  slug: string;
  /**
   * Естественное описание изображения, не перечень ключей. Обязателен до перевода в review (проверка полноты — задача Э1-08).
   */
  alt?: string | null;
  /**
   * Подпись или текст поздравления, видимый на странице.
   */
  caption?: string | null;
  /**
   * Описание открытки для страницы (видимый текст).
   */
  description?: string | null;
  /**
   * Meta description. Задаётся отдельно от описания (ТЗ §8.1); совпадения по каталогу проверяются при сохранении (задача Э5-01).
   */
  metaDescription?: string | null;
  /**
   * Условия использования изображения. Из этого поля берутся license и copyrightNotice в JSON-LD ImageObject (этап 3): если условия у открытки общие, поле остаётся пустым и подставляются условия проекта.
   */
  usageTerms?: string | null;
  /**
   * Подборки, в которые входит открытка (m:n, ТЗ §8.1). ПЕРВАЯ — основная: из неё строятся хлебные крошки. Открытка входит в несколько подборок БЕЗ дублирования URL: канонический адрес карточки остаётся один навсегда — /otkrytki/<slug>, копии карточки внутри подборок не создаются.
   */
  collections?: (number | Collection)[] | null;
  /**
   * draft → review → published. Перевод в published — осознанное действие человека с ролью admin; сервисный аккаунт ai-editor доводит запись до review.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * index,follow — только для published и только по решению администратора при выполнении условий п. 5.1 SEO ТЗ (подтверждённый спрос, отдельный интент, достаточный объём, уникальные тексты, страница в навигации).
   */
  robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
  /**
   * Пусто = self-canonical (норма). Переопределение — только администратор и только путём от корня: абсолютный URL собирается из SITE_URL, вручную его вписывать нельзя.
   */
  canonical?: string | null;
  /**
   * Дата первой публикации. Ставится автоматически при первом переводе в published (Э1-08) и далее не меняется: по ней определяется, что URL уже был известен поисковику.
   */
  publishedAt?: string | null;
  /**
   * Меняется ТОЛЬКО при содержательном обновлении: это lastmod в sitemap. Техническая правка (опечатка, служебное поле) дату не двигает — иначе lastmod перестаёт что-либо означать для поисковика.
   */
  updatedContentAt?: string | null;
  /**
   * Перцептивный хеш изображения. Считает @otkritka/images при загрузке (задача Э2-05); снаружи не пишется, иначе поиск визуальных дублей можно было бы обойти подстановкой чужого значения.
   */
  pHash?: string | null;
  /**
   * Служебные поля постоянства URL файлов. Заполняются пайплайном изображений (Э2-05, Э2-06) и не пишутся снаружи ни через админку, ни через API.
   */
  derivative?: {
    /**
     * СОХРАНЁННЫЙ ключ производной (<префикс>/<revision>/<имя>), условие C1. Хранится, а не пересчитывается: сегодня ключ — функция от описания, лимита длины имени и таблицы транслитерации, поэтому правка заголовка или пополнение таблицы дали бы другой путь при том же содержимом. Фиксируется при первой публикации и далее неизменяем.
     */
    keyBase?: string | null;
    /**
     * Имя файла на транслите вместе с суффиксом уникальности, присвоенное при загрузке. Хранится отдельно от ключа, потому что при замене изображения меняется только revision, а имя остаётся тем же.
     */
    nameStem?: string | null;
    /**
     * Число N в суффиксе -N, уникализирующем имя файла (решение человека, блок 5 п. 3). Присваивается ОДИН раз при загрузке и хранится: если вычислять его заново, удаление ранней записи освободило бы N и путь другой записи изменился бы незаметно. После удаления N не переиспользуется.
     */
    nameSuffix?: number | null;
    /**
     * Короткий хеш байтов оригинала (решение Ч-28, вариант «а»). Меняется ТОЛЬКО при замене изображения — тогда меняются URL производных при неизменном URL карточки (ТЗ §6.7). Выводить revision из updatedAt или счётчика сохранений запрещено: каждое сохранение переписывало бы URL всех производных (условие C2).
     */
    revision?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Подборки и посадочные. URL собирается из цепочки родителей: /podborki/<группа>/<повод>/<уточнение>. Порядок только «повод → уточнение». Новая запись — draft с noindex; публикует и открывает в индекс только человек.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  /**
   * Заголовок страницы (title). Уникален в пределах каталога — совпадения проверяются при сохранении (задача Э5-01). Смена заголовка URL не меняет.
   */
  title: string;
  /**
   * H1 страницы. Пустой — совпадает с title (ТЗ §8.1).
   */
  h1?: string | null;
  /**
   * Один сегмент URL. Итоговый путь собирается из пути родителя и этого сегмента, например /podborki/prazdniki/8-marta/mame. Slug праздника с фиксированной датой — <число>-<месяц> (8-marta, 9-maya); без фиксированной даты — короткое название (paskha, novyy-god), решение Ч-04-4. Год в URL ежегодного праздника не добавляется. Неизменяем после первой публикации (смена — только вместе с одиночным 301, задача Э1-09).
   */
  slug: string;
  /**
   * ИТОГОВЫЙ путь подборки. Считается хуком из цепочки родителей и хранится с уникальным индексом БД: уникальность URL не может держаться на проверке запросом перед записью — два одновременных сохранения через API прошли бы её оба. Снаружи не пишется ни через админку, ни через API.
   */
  path?: string | null;
  /**
   * Определяет, куда узел можно вложить: группа — только в корень /podborki, повод — под группу, уточнение — под группу или под повод. Порядок только «повод → уточнение» (решение Ч-04-7): праздник под адресатом не создаётся никогда. Вида под стиль и настроение нет намеренно — по решению Ч-04-3 это фильтр без собственных URL.
   */
  nodeKind: 'group' | 'occasion' | 'recipient';
  /**
   * Родительский узел. Пусто — узел верхнего уровня (прямо под /podborki). Смена родителя меняет URL этой подборки и всех вложенных, поэтому после первой публикации она возможна только вместе с одиночным 301 (задача Э1-09).
   */
  parent?: (number | null) | Collection;
  /**
   * Вводный текст страницы (ТЗ §8.1). Должен быть уникальным и осмысленным: шаблонный текст с заменой пары слов — прямой запрет п. 23 SEO ТЗ, а уникальность вводного текста входит в условия открытия страницы в index,follow (п. 5.1).
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Meta description. Совпадения по каталогу проверяются при сохранении (задача Э5-01).
   */
  metaDescription?: string | null;
  /**
   * draft → review → published. Перевод в published — осознанное действие человека с ролью admin; сервисный аккаунт ai-editor доводит запись до review.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * index,follow — только для published и только по решению администратора при выполнении условий п. 5.1 SEO ТЗ (подтверждённый спрос, отдельный интент, достаточный объём, уникальные тексты, страница в навигации).
   */
  robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
  /**
   * Пусто = self-canonical (норма). Переопределение — только администратор и только путём от корня: абсолютный URL собирается из SITE_URL, вручную его вписывать нельзя.
   */
  canonical?: string | null;
  /**
   * Дата первой публикации. Ставится автоматически при первом переводе в published (Э1-08) и далее не меняется: по ней определяется, что URL уже был известен поисковику.
   */
  publishedAt?: string | null;
  /**
   * Меняется ТОЛЬКО при содержательном обновлении: это lastmod в sitemap. Техническая правка (опечатка, служебное поле) дату не двигает — иначе lastmod перестаёт что-либо означать для поисковика.
   */
  updatedContentAt?: string | null;
  /**
   * Ответственный редактор подборки. По умолчанию — администратор (решение Ч-16): даже если запись создал сервисный аккаунт ai-editor, ответственным остаётся человек, потому что решение о публикации принимает он.
   */
  responsibleEditor?: (number | null) | User;
  /**
   * Смежные подборки (m:n, ТЗ §8.1). Из них строится перелинковка: она же закрывает требование «нет страниц-сирот» — каждая индексируемая страница достижима за ≤ 4 перехода от главной.
   */
  related?: (number | Collection)[] | null;
  /**
   * Календарь праздников — официальный календарь РФ, даты вводятся здесь (решение Ч-12). Дата готовности по умолчанию — за 45 дней до праздника; окно ТЗ §8.6 — 4–8 недель.
   */
  seasonal?: {
    /**
     * Дата праздника по официальному календарю РФ. Списка праздников в коде нет намеренно: он разошёлся бы с календарём при первом переносе выходных, а обновлять его пришлось бы деплоем.
     */
    holidayDate?: string | null;
    /**
     * Дата готовности. Пусто — ставится автоматически за 45 дней до праздника (Ч-12); заданное значение не перезаписывается.
     */
    readyBy?: string | null;
    /**
     * С какого дня подборка показывается в сезонном блоке главной (ТЗ §8.1). Даты показа переключают БЛОК на главной и не создают отдельных URL.
     */
    showFrom?: string | null;
    /**
     * По какой день подборка показывается в сезонном блоке главной.
     */
    showUntil?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Две роли: admin (человек, полные права) и ai-editor (сервисный аккаунт с API-ключом, доводит контент до review).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * admin — полные права, включая публикацию и index,follow. ai-editor — черновики, метаданные, привязка к подборкам и перевод draft → review.
   */
  role: 'admin' | 'ai-editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Одиночные 301 и 410. Цепочки запрещены: новый редирект, создающий цепочку, схлопывается автоматически, а петля отклоняется.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Старый путь от корня сайта, например /otkrytki/staraya-otkrytka. Уникален: два правила для одного пути сделали бы ответ зависимым от порядка строк.
   */
  from: string;
  /**
   * Новый путь от корня сайта. Обязателен для 301 и обязан быть ПУСТЫМ для 410. Абсолютный URL недопустим: хост собирается из SITE_URL.
   */
  to?: string | null;
  /**
   * Только 301 и 410. Временных редиректов в модели нет: перенос страницы — постоянное решение, а 302 не передаёт сигналы старого URL новому.
   */
  code: '301' | '410';
  /**
   * Кто создал правило: заполняется сервером и не приходит из запроса.
   */
  createdBy?: (number | null) | User;
  /**
   * Зачем создан редирект: причина переноса, ссылка на задачу.
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cards';
        value: number | Card;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards_select".
 */
export interface CardsSelect<T extends boolean = true> {
  title?: T;
  h1?: T;
  slug?: T;
  alt?: T;
  caption?: T;
  description?: T;
  metaDescription?: T;
  usageTerms?: T;
  collections?: T;
  status?: T;
  robots?: T;
  canonical?: T;
  publishedAt?: T;
  updatedContentAt?: T;
  pHash?: T;
  derivative?:
    | T
    | {
        keyBase?: T;
        nameStem?: T;
        nameSuffix?: T;
        revision?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  h1?: T;
  slug?: T;
  path?: T;
  nodeKind?: T;
  parent?: T;
  intro?: T;
  metaDescription?: T;
  status?: T;
  robots?: T;
  canonical?: T;
  publishedAt?: T;
  updatedContentAt?: T;
  responsibleEditor?: T;
  related?: T;
  seasonal?:
    | T
    | {
        holidayDate?: T;
        readyBy?: T;
        showFrom?: T;
        showUntil?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  code?: T;
  createdBy?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}